### ISSUE TITLE
Hubs DPX Communal Space - Workshop Space

### ISSUE THREAD

**Issue by fernzharp** [mozilla/dpx-planning-and-intake#200]
Creating the Hubs room for Workshop to take place: [https://app.zenhub.com/workspaces/dpx-hubs-5fb2cede17eb69001d393a6a/issues/mozilla/dpx/138](url)

**Comment by fernzharp** [comment]
Workshop version 1: [Version 1](https://hubs.mozilla.com/42BQfkU/dpx-workshop-1/)
Workshop version 2: [Version 2](https://hubs.mozilla.com/EoMKGLu/finished-instructive-adventure)
Workshop version 3: [Version 3](https://hubs.mozilla.com/X9CFqPa/finished-adorable-exploration)

**Comment by DPX-designer** [comment]
Feedback and approval was provided in Slack.
Space is ready for the workshop.
