### ISSUE TITLE
Top Line Summary for usability test (new interface)

### ISSUE THREAD

**Issue by DPX-designer** [mozilla/dpx-planning-and-intake#226]
Provide a Top Line Summary to the Hubs Design team which captures the feedback and observation of users trying the new Hubs interface.

**Comment by glogigi** [comment]
Recommendation: https://docs.google.com/document/d/1w4I5jOSGW43iW6PO7vcT8us2MbTxG8RX3LJ6mgWFc8Y/edit?usp=sharing
